services:
    app:
        build:
            context: ..
            dockerfile: deploy/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        environment:
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
            - APP_ENV=local
            - APP_DEBUG=true
            - QUEUE_CONNECTION=database
        volumes:
            - ../:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/node_modules
            - sqlite_data:/var/www/html/database
        networks:
            - laravel_network
        command: ["/usr/local/bin/start.sh"]

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ../:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

volumes:
    sqlite_data:
        driver: local

networks:
    laravel_network:
        driver: bridge
